[tool.poetry]
name = "{project-name}"
version = "1.0.0"
description = "A brief description of your project."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "{project-name}", from = "src" }
]

# Main project dependencies
[tool.poetry.dependencies]
python = "^3.8"
# Example dependencies (add your specific requirements)
numpy = "^1.21"
pandas = "^1.3"

# Development dependencies
[tool.poetry.dev-dependencies]
pytest = "^6.2"             # for testing
jupyter = "^1.0.0"          # for running notebooks in the examples folder

# Scripts can also be specified here if necessary
# Defining a script
[tool.poetry.scripts]
example-script = "scripts.example_module:main_function"
# can be run with: poetry run example-script


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
